name: Sync Labels

on:
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  sync-labels:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout shared .github repository
        uses: actions/checkout@v4
        with:
          repository: nullsaf/.github
          path: shared-config

      - name: Sync labels
        uses: micnncim/action-label-syncer@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          manifest: shared-config/labels.yml
          delete-other-labels: true